# Generated by Django 5.0 on 2023-12-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='Uncategorized', max_length=255),
        ),
    ]
